
//Restaurant reducer
export const GET_RESTAURANT_LIST = "GET_RESTAURANT_LIST";
export const GET_SELECTED_RESTAURANT_DETAILS = "GET_SELECTED_RESTAURANT_DETAILS";
export const APPEND_RESTAURANT_LIST="APPEND_RESTAURANT_LIST";
export const GET_TOTAL_RESTAURANT="GET_TOTAL_RESTAURANT";

//Location reducer
export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const GET_SELECTED_LOCATION_DETAILS = "GET_SELECTED_LOCATION_DETAILS";

//Loading reducer
export const SET_LOADING_RESTAURENT_FETCHING="SET_LOADING_RESTAURENT_FETCHING";