
//Restaurant reducer
export const GET_RESTAURANT_LIST = "GET_RESTAURANT_LIST";
export const GET_SELECTED_RESTAURANT_DETAILS = "GET_SELECTED_RESTAURANT_DETAILS";

//Location reducer
export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const GET_SELECTED_LOCATION_DETAILS = "GET_SELECTED_LOCATION_DETAILS";